image: gradle:7.4-jdk11
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update -qy
  - apt-get install -y ruby-dev

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

test:
  stage: test
  script:
    - export SPRING_PROFILES_ACTIVE=test
    - gradle check --stacktrace
    - cat build/reports/jacoco/test/html/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    paths:
      - build/reports/jacoco/*
    expire_in: 1 day

deployment:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    - export HEROKU_API_KEY=$HEROKU_API_KEY
  environment:
    name: production
    url: $HEROKU_APP_HOST
  only:
    - develop
    - main
